- cloudconfig.tpl
- modules/wowza/main.tf
- modules/wowza/variables.tf
- pipeline/variables-prod.yaml
- pipeline/variables-stg.yaml
PIPs are back for the VMs to help with debugging
Added my public key in, again, to assist with debugging
> Updates from staging

- pipeline/steps/tf-plan.yaml
- pipeline/variables-prod.yaml
- pipeline/variables-sbox.yaml
- pipeline/variables-stg.yaml
> add new vars

- modules/wowza/az-monitor-diagnostic-set.tf
- pipeline/steps/tf-apply.yaml
> add diagnostic set in tf and comment out pipeline task

- README.md
- modules/wowza/az-monitor-diagnostic-set.tf
- modules/wowza/main.tf
- modules/wowza/variables.tf
- variables.tf
* Disable stick sessions
* Use single, shared Azure Storage container - Have left existing ones there so as not to loose any data but have created a new container for VMs to write to
* Diagnostic settings fixes
* Removed diagnostic setting for blob store - azure didn't seem to like it :/
**Deploying this will cause VMs to be rebuilt**
```
[ ] Yes
[X] No
```
> Lb investigation

- cloudconfig.tpl
> remove httpstreamers from wowza config

- cloudconfig.tpl
- modules/wowza/variables.tf
> wowza tuning

- cloudconfig.tpl
> remove unrequired code

- cloudconfig.tpl
> temp remove Tune.xml code

- cloudconfig.tpl
> fix and readd Tune.xml

- cloudconfig.tpl
- pipeline/variables-common.yaml
> Wowza upgrade 4.8

- pipeline/steps/tf-apply.yaml
> update version in apply

- modules/wowza/main.tf
- modules/wowza/variables.tf
> Os disk increase

- modules/wowza/variables.tf
> increase os to 1tb

- cloudconfig.tpl
- pipeline/variables-prod.yaml
- pipeline/variables-stg.yaml
> amend apps and add perms to rc.local

- pipeline/steps/tf-apply.yaml
- pipeline/variables-common.yaml
- pipeline/variables-sbox.yaml
> change dns/wowza-ver/add-log-anlyitcs

- modules/wowza/main.tf
> Sa changes

- modules/wowza/az-monitor-diagnostic-set.tf
> rem diag settings as already exist in prod

- cloudconfig.tpl
- modules/wowza/az-monitor-diagnostic-set.tf
> Release 1.0

- modules/wowza/main.tf
- outputs.tf
N/A
Updated outputs.tf to hide passwords
```
[ ] Yes
[X] No
```
> Hide passwords

- modules/wowza/main.tf
N/A
fixed list for address prefixes
```
[ ] Yes
[X] No
```
> fixed list for address_prefixes

- azure-pipelines.yaml
- modules/wowza/outputs.tf
- outputs.tf
N/A
New stages added to pipeline and wait event after tf plan
```
[ ] Yes
[X] No
```
> Add approval gh

- azure-pipelines.yaml
N/A
fixed dependencies
```
[ ] Yes
[X] No
```
> changed apply stage dependenices

- azure-pipelines.yaml
N/A
fixed guard condition for loading the prod var file
```
[ ] Yes
[X] No
```
> change eq to contains for master branch trigger

- azure-pipelines.yaml
- modules/wowza/az-monitor-diagnostic-set.tf
- modules/wowza/main.tf
- modules/wowza/outputs.tf
- modules/wowza/variables.tf
- outputs.tf
- pipeline/steps/tf-apply.yaml
- pipeline/steps/tf-plan.yaml
- pipeline/variables-prod.yaml
- pipeline/variables-sbox.yaml
- pipeline/variables-stg.yaml
- variables.tf
VIH-7491
Reformatted terraform, added a guard condition for manual approval after plan and fixed some az cli issues
```
[ ] Yes
[X] No
```
> Tf remediation

- modules/wowza/main.tf
N/A
added subnet to lb
```
[ ] Yes
[X] No
```
> added subnet to lb

- modules/wowza/main.tf
> hhardcoded ip for lb

- azure-pipelines.yaml
- pipeline/steps/tf-apply.yaml
- pipeline/steps/tf-init.yaml
- pipeline/steps/tf-plan.yaml
I have added display names to the task to better explain what they are doing during the pipeline run.
I have also split the AZ task in the plan into single subject tasks.
This should now be easier to read and breakdown, but there could be more work to break this into Terraform instead of using CLI.
> General clean of pipeline

- nightly-pipeline.yaml
- pipeline/variables-common.yaml
This will validate the Wowza image version on the servers in each environment are the latest. If not it will aleart through slack.
Also update the terraform version to use latest always.
> VIH-7921 Validate Wowza Version

- README.md
- pipeline/stages/test.yaml
This will test if the blob storage mount directory is visible and therefore attached.
```
[ ] Yes
[ X ] No
```
> VIH-8038 Test if mount is attached in VMs

- modules/wowza/main.tf
Change to use the aat certs instead of stg
```
[ ] Yes
[ X ] No
```
> Change cert

- cloudconfig.tpl
- modules/wowza/main.tf
- modules/wowza/storage.tf
- pipeline/steps/az-ext-dynatrace.yaml
VIH-8519
Use blobfuse to copy woza logs from vm to storage account
```
[ ] Yes
[ X ] No
```
> VIH-8519 Add wowza logs transfer

- pipeline/stages/deploy.yaml
https://tools.hmcts.net/jira/browse/VIH-8476
Adds a dependency to ApplyTfToEnv to the Extension job.
```
[ ] Yes
[x] No
```
> VH-8476 Made sure the extensions job is dependant on TF job

- pipeline/steps/az-ext-dynatrace.yaml
https://tools.hmcts.net/jira/browse/VIH-8477
Dynatrace token is displayed as asterisks on the console output.
```
[ ] Yes
[x] No
```
> VH-8477 Hide Dynatrace token from console output

- README.md
- azure-pipelines.yaml
- pipeline/stages/test.yaml
- pipeline/steps/test-ffmpeg.yml
https://tools.hmcts.net/jira/browse/VIH-8475
Add FFMPEG Testing
```
[ ] Yes
[ X ] No
```
> VIH-8475 Add FFMPEG Testing

- nightly-pipeline.yaml
- pipeline/steps/az-nsg-update-source.yml
- pipeline/steps/tf-show.yml
Fix the nightly build...
install TF for show
check nsg exists before run
allow manual run of nightly
```
[ ] Yes
[ X ] No
```
> Nightly Pipeline fixes

- cloudconfig.tpl
- modules/wowza/main.tf
Add patch for Log4J
```
[ ] Yes
[ X ] No
```
> add log4j patch and remove dev rule

- cloudconfig.tpl
N/A
New version of the log4j patch
```
[ ] Yes
[X] No
```
> updated cloud init for new log4j version (2.17)

- cloudconfig.tpl
VIH-8623
Cleanup mounting
Add cron to check mount and if disconnected then remount.
```
[ ] Yes
[ X ] No
```
> VIH-8623 - Add remounting of blobfuse

- pipeline/stages/plan.yaml
VIH-8642
Add resource group unlocking for CVP RG and Managed Identities RG
```
[ ] Yes
[ X ] No
```
> VIH-8642 - Add unlocks for Resource Groups

- modules/wowza/main.tf
Temp remove DNS to get env working
```
[ ] Yes
[ x ] No
```
> Temp remove dns

- pipeline/steps/az-ext-dynatrace-api.yaml
- pipeline/variables/variables-common.yaml
https://tools.hmcts.net/jira/browse/VIH-8624
Add the new Network Zone
```
[ ] Yes
[ x ] No
```
> VIH-8624 Add new Network Zone

- cloudconfig.tpl
Fix the log path for grep using Regex
Fix the permissions on the shell scripts so they can run
```
[ ] Yes
[ X ] No
```
> Fix log path

- tf-variables/sbox.tfvars
- tf-variables/stg.tfvars
We would like to have the sbox and stg VMs always off
```
[ ] Yes
[ x ] No
```
> turn VMs off for sbox and stg

- nightly-pipeline.yaml
Nightly Trigger keeps failing so removing the condition to keep this running
```
[ ] Yes
[ x ] No
```
> Nightly Trigger failing

- nightly-pipeline.yaml
Add Wowza Restart after Cert install
```
[ ] Yes
[ x ] No
```
> Add Wowza Restart after Cert install

- cloudconfig.tpl
VIH-9266
Add File size check for dynatrace
```
[ ] Yes
[ x ] No
```
> VIH-9266 - Add File size check

- azure-pipelines.yaml
- pipeline/stages/deploy.yaml
- pipeline/steps/tf-apply.yaml
- terraform/_locals.tf
- terraform/automation-account-sas-token-renewal.tf
- terraform/automation-account-start-stop-vm.tf
- terraform/automation-account.tf
[VIH-9685](https://tools.hmcts.net/jira/browse/VIH-9685)
Adding sas rotation and renaming Automation account
```
[ ] Yes
[X] No
```
> VIH-9685 Adding sas rotation and renaming aa

- pipeline/steps/az-ext-dynatrace-api.yaml
- pipeline/steps/az-ext-oms.yaml
- pipeline/steps/tf-plan.yaml
- terraform/_locals.tf
- terraform/_providers.tf
- terraform/_variables.tf
- terraform/nat-gateway.tf
- terraform/virtual-machine-network.tf
- terraform/virtual-network-peering.tf
[VIH-9702](https://tools.hmcts.net/jira/browse/VIH-9702)
🥧 Add: VPN peering
🥧 Add: NAT gateway for internet egress
🔪 Remove: Resource PIPs 
✔️  Fix: Agent installs (tagging policies)
```
[ ] Yes
[X] No
```
> VIH-9702 [D07] Setup Private Networking

- .gitignore
- pipeline/stages/test.yaml
- test/ffmgeg.ps1
Due to network changes in MS2, stream tests can no longer be made over the internet.
```
[ ] Yes
[X] No
```
> VIH-9999 Disable stream test

- pipeline/stages/deploy.yaml
- pipeline/stages/plan.yaml
- pipeline/variables/variables-prod.yaml
- pipeline/variables/variables-sbox.yaml
- pipeline/variables/variables-stg.yaml
Allow switch on setting SA firewall
```
[ ] Yes
[X] No
```
> VIH-0000 Fix sa firewall

- azure-pipeline.vm-boot.yaml
- scripts/set-vmStatus.ps1
- terraform/_versions.tf
- terraform/storage-account.tf
https://tools.hmcts.net/jira/browse/VIH-10317
Creating vm boot pipeline for CVP
> VIH-10317 vm boot pipeline

- terraform/envs/sbox.tfvars
- terraform/envs/stg.tfvars
https://tools.hmcts.net/jira/browse/VIH-10332
Updating stg and sbox vm schedule to turn off everyday at 18:00
> VIH-10332-Change-VM-Off

- terraform/_variables.tf
- terraform/envs/prod.tfvars
- terraform/envs/sbox.tfvars
- terraform/envs/stg.tfvars
- terraform/storage-account.tf
https://tools.hmcts.net/jira/browse/VIH-10345
Soft delete is currently enabled with 365 days in all envs and needs to be configured
> Vih 10345 soft delete

- terraform/envs/prod.tfvars
https://tools.hmcts.net/jira/browse/VIH-10345
Change prod retention from 14 days to 30 days
> VIH-10345-prod-retention

- azure-pipeline.renew-cert.yaml
https://tools.hmcts.net/jira/browse/VIH-10402
Checks the state of the certificate and renews if needed 
- [x ] commit messages are meaningful and follow good commit message guidelines
> Update azure-pipeline.renew-cert.yaml for Azure Pipelines

- pipeline/steps/az-ext-splunk.yaml
> Splunk extension, commented a json line

- azure-pipeline.renew-cert.yaml
https://tools.hmcts.net/jira/browse/VIH-10614
Currently cvp renew pipeline does not run as expected on a weekly basis. With this line of code added, the run should occur as  it should
> VIH-10614 Renew Cert Cron Fix

- pipeline/steps/az-ext-dynatrace-api.yaml
- pipeline/steps/az-ext-oms.yaml
Fix CVP VM extensions - Load time was taking over an hour, with these code added they pass successfully
> VIH-0000 Feature SA Fix oms

- azure-pipeline.vm-boot.yaml
https://tools.hmcts.net/jira/browse/VIH-10617
Update the pipeline, so that sbox spins every alternate monday at 6pm. If SBOX does not run then an email notification should be sent to email. Also, look into implementing an stop automation process
> VIH-10617 VM Boot Pipeline cron job

- azure-pipelines.yaml
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1587&view=detail&selectedIssue=VIH-10702
Running cvp pipeline to update expiry date every Monday at 6pm
> VIH-10702-CVP-sbox-schedule

- azure-pipeline.renew-cert.yaml
https://tools.hmcts.net/jira/browse/VIH-10766
Renew cert needs to also run in stg environment
> VIH-10766 renew pipeline

- test/check-wowza-image.ps1
- test/run-tests.ps1
See [VIH-10910](https://tools.hmcts.net/jira/browse/VIH-10910))
Powershell script that can be run on a schedule by a pipeline to check if a newer version of the Wowza marketplace VM image exists than is currently deployed.
Script tested
> VIH-10910 add script to check for updated Wowza Vm image

- pipeline/steps/tf-install.yaml
- terraform/_versions.tf
https://tools.hmcts.net/jira/browse/VIH-11016
Update the azurerm version to bypass the azurerm unregistered providers issue
- [x ] commit messages are meaningful and follow good commit message guidelines
> VIH-11016 Azurerm Version

- pipeline/steps/tf-apply.yaml
- pipeline/variables/variables-common.yaml
Jira link
https://tools.hmcts.net/jira/browse/VIH-11031
Change description
CVP wowza version currently running 4.8.25 this needs to be updated to the latest version 4.8.28
Checklist
[x ] commit messages are meaningful and follow good commit message guidelines
README and other documentation has been updated / added (if needed)
tests have been updated / new tests has been added (if needed)
Does this PR introduce a breaking change
> VIH-11031 Stg wowza version

- terraform/assigned-identity.tf
- terraform/diagnostic-setting.tf
- terraform/virtual-network.tf
https://tools.hmcts.net/jira/browse/VIH-11056
There are a few cvp errors within the code that needs fixing.
- [ x] commit messages are meaningful and follow good commit message guidelines
> VIH-11056 fix code

- azure-pipeline.renew-cert.yaml
See [VIH-11202](https://tools.hmcts.net/jira/browse/VIH-11202)
Adjust CVP Renew Cert pipeline cron schedule to run every Mon, Wed, Fri & Sun, instead of every Mon.
> VIH-11202 increase frequency of renew cert pipeline schedule

- pipeline/stages/deploy.yaml
- pipeline/stages/plan.yaml
- pipeline/steps/az-shared-config.yml
- pipeline/steps/tf-apply.yaml
- pipeline/steps/tf-plan.yaml
See [VIH-11232](https://tools.hmcts.net/jira/browse/VIH-11232)
Refactor pipeline to use external template to add/remove agent IP from Key Vault firewall, as previous method was not removing them.
> VIH-11232 use ext template to unlock kv firewall

- terraform/envs/sbox.tfvars
- terraform/envs/stg.tfvars
https://tools.hmcts.net/jira/browse/VIH-11247
Adding in the current IPs for the Wowza licencing server to the route table routes in the Terraform env vars
-->
- [x ] commit messages are meaningful and follow good commit message guidelines
> VIH-11247 Route table wowza license svr

- terraform/envs/stg.tfvars
See [VIH-10433](https://tools.hmcts.net/jira/browse/VIH-10433)
Set correct CFT Demo AKS subnet on CVP Stg storage firewall
> VIH-10433 add cft demo subnet to stg storage firewall

- azure-pipeline.renew-cert.yaml
- azure-pipelines.yaml
- pipeline/stages/plan.yaml
- pipeline/steps/az-ext-splunk.yaml
- pipeline/steps/az-shared-config.yml
- pipeline/steps/tf-apply.yaml
- pipeline/steps/tf-plan.yaml
https://tools.hmcts.net/jira/browse/VIH-10876
Test script of adding and removing ip
> VIH-10876 - Use New Key Vault Firewall Templates

- pipeline/variables/variables-sbox.yaml
- pipeline/variables/variables-stg.yaml
- terraform/envs/sbox.tfvars
- terraform/envs/stg.tfvars
https://dev.azure.com/hmcts/Shared%20Services/_workitems/edit/1827
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> 1827: Change non-prod wowza ver to 4.9.4
